server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        service-name: gateway
        health-check-interval: 10s
        health-check-path: /actuator/health
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**

        - id: portfolio
          uri: lb://portfolio
          predicates:
            - Path=/api/portfolio/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
